# Dependencies
markdown:	kramdown
highlighter: rouge

# Permalinks
permalink:	/blog/:title

# Setup
title:		Stefanos Michael
tagline:	
description:	'My personal blog.'
url:		http://stefanos990.github.io

author:
  name:		'Stefanos Michael'
  url:		http://stefanos990.github.io

paginate:	5

# Custom vars
icon:		/assets/images/icon.png
cover:		/assets/images/cover.jpg

social:
  - icon: facebook
    url:  https://facebook.com/stefanos990
    desc: Add me on Facebook

  - icon:	twitter
    url:	https://twitter.com/stefanos990
    desc:	Follow me on Twitter

  - icon: linkedin
    url:  http://t.co/ujtnCQDvC6
    desc: Follow me on LinkedIn

  - icon:	flickr
    url:	https://www.flickr.com/people/stefanos990/
    desc:	Follow me on Flickr
    
  - icon: mail
    url: mailto:stefanos990@outlook.com
    desc: Contact me


    
menu:
  - title:	home
    url:	/

  - title:  projects
    url:  /projects

  - title:  blog
    url:  http://blog.stefanos990.com

  - title: gallery
    url: /gallery

  - title: CV
    url: /cv


copyright:
  author:	Stefanos Michael
  url:		http://stefanos990.github.io
  type_url:	http://creativecommons.org/licenses/by-nc/2.5
