# Dependencies
markdown:	kramdown
highlighter: rouge

# Permalinks
permalink:	/blog/:title

# Setup
title:		Stefanos Michael
tagline:	
description:	'My personal blog.'
url:		https://stefanos990.github.io

author:
  name:		'Stefanos Michael'
  url:		https://stefanos990.github.io

paginate:	5

# Custom vars
icon:		/assets/images/icon.png
cover:		/assets/images/cover.jpg

social:
  - icon: facebook
    url:  https://facebook.com/stefanos990
    desc: Add me on Facebook

  - icon:	twitter
    url:	https://twitter.com/stefanos990
    desc:	Follow me on Twitter

  - icon: linkedin
    url:  https://t.co/ujtnCQDvC6
    desc: Follow me on LinkedIn

  - icon:	instagram
    url:	https://www.instagram.com/stefanos990/
    desc:	Follow me on Instagram
    

    
menu:
  - title:	home
    url:	/

  - title:  projects
    url:  /projects

  - title: CV
    url: /cv

  - title: gallery
    url: /gallery

  - title:  blog
    url:  https://blog.stefanos990.com


copyright:
  author:	Stefanos Michael
  url:		https://stefanos990.github.io
  type_url:	https://creativecommons.org/licenses/by-nc/2.5
